"use client";

import { useEffect, useMemo, useState } from "react";
import { Play, Search } from "lucide-react";

type Book = { title: string; price_gbp: number; rating_text: string; availability_text: string; product_url: string };
type Report = { valid_records?: number; invalid_records?: number; duration_ms?: number; cache_hits?: number; failed_pages?: number };

export default function ScraperPage() {
  const [books, setBooks] = useState<Book[]>([]); const [report, setReport] = useState<Report | null>(null); const [query, setQuery] = useState(""); const [status, setStatus] = useState("Loading scraper artifacts...");
  const load = async () => { const response = await fetch("/api/backend/api/scraper/data", { cache: "no-store" }); const data = await response.json(); setBooks(data.books ?? []); setReport(data.report); setStatus(response.ok ? "Artifacts loaded" : data.error ?? "Backend unavailable"); };
  useEffect(() => { void load(); }, []);
  const trigger = async () => { setStatus("Scraper running politely..."); const response = await fetch("/api/backend/api/scraper/trigger", { method: "POST" }); setStatus(response.ok ? "Scraper completed" : "Scraper failed"); void load(); };
  const filtered = useMemo(() => books.filter((book) => book.title.toLowerCase().includes(query.toLowerCase())), [books, query]);
  return <section className="mx-auto max-w-7xl px-6 py-10"><Header title="Polite Scraper" subtitle="Browse the validated Books to Scrape dataset and trigger the resilient pipeline." /><div className="mb-5 flex flex-wrap items-center gap-3"><button onClick={() => void trigger()} className="flex items-center gap-2 rounded-lg bg-emerald-300 px-4 py-2 text-sm font-medium text-slate-950"><Play size={16} />Run scraper</button><span className="text-sm text-slate-500">{status}</span></div><div className="mb-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{[["Valid records", report?.valid_records ?? 0], ["Cache hits", report?.cache_hits ?? 0], ["Failed pages", report?.failed_pages ?? 0], ["Invalid", report?.invalid_records ?? 0], ["Duration", `${report?.duration_ms ?? 0} ms`]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="relative mb-4 max-w-sm"><Search className="absolute left-3 top-2.5 text-slate-500" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter books" className="w-full rounded-lg border border-white/10 bg-slate-950 py-2 pl-9 pr-3 text-sm outline-none focus:border-emerald-300" /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr><th className="py-3">Title</th><th>Price</th><th>Rating</th><th>Availability</th></tr></thead><tbody>{filtered.map((book) => <tr key={book.product_url} className="border-b border-white/5"><td className="py-3 pr-4 text-slate-200">{book.title}</td><td>£{book.price_gbp}</td><td>{book.rating_text}</td><td className="text-slate-400">{book.availability_text}</td></tr>)}</tbody></table></div></div></section>;
}
function Header({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-8"><p className="text-xs uppercase tracking-[0.22em] text-emerald-300">Unified service</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{title}</h1><p className="mt-3 text-slate-400">{subtitle}</p></div>; }
